Types for members
Dlubal-Software/Dlubal_JavaScript_Library pull request #10
Opened 2022-01-27 11:36 UTC by david-liska

2022-01-31 10:27 UTC, jarabroz requested changes
Fix issues. Prehaps add more examples to high_level_functions_examples

2022-01-31 12:23 UTC, jarabroz commented on includes/TypesForMembers/MemberEccentricity.js
> +* @param	{String}	alignment			Alignment, for more info look at private function setRelativeValues
Katerina is using this function https://github.com/Dlubal-Software/Dlubal_JavaScript_Library/blob/28a5413fc76e93fe72bc61d1ba48323e5bee2893/includes/AnalysisSettings/StaticAnalysisSettings.js#L2 and also some const to switch from human readable text to enumeration.
Please discuss it with her and try to find unified approach

2022-02-01 09:18 UTC, david-liska commented on includes/TypesForMembers/MemberNonlinearity.js
> +	setParameters(this.memberNonlinearity, [nt], "tension_force");
nc, nt and ux replaced by readable variable names (nc - compression_force, nt - tension_force, ux - slippage)

2022-02-04 10:09 UTC, jarabroz approved these changes

2022-02-04 10:09 UTC, merged