10790 rsection loading internal forces
Dlubal-Software/Dlubal_JavaScript_Library pull request #75
Opened 2022-09-27 12:20 UTC by david-liska

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples
- [ ] Own example attached to Pull Request

**Test Configuration**:
* RFEM / RSTAB / RSECTION version:
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-30 12:24 UTC, jarabroz commented on examplesRSECTION/high_level_functions_demos/load_cases_combinations_internal_forces_demo.js
> +var load_case2 = new RSectionLoadCase(undefined, "PRESTRESS_P", "First load case", false);
This souble be "Second load case"

2022-10-03 10:39 UTC, jarabroz requested changes

2022-10-03 10:39 UTC, jarabroz commented on includes/InternalForces/RsectionInternalForces.js
> +
Could be fine to have also prototype for assigment all internal forces

2022-10-03 10:39 UTC, jarabroz commented on includes/Loading/RsectionLoadCombination.js
> + * @param {Array} loadCases     Load cases
let's do it same as in RFEM -> [[load_case_no, factor],[]....]

2022-10-03 10:39 UTC, jarabroz commented on includes/Loading/RsectionLoadCase.js
> +
Add prototypes for GetLoadCase and GetNo - could be useful if I want to make load combination and I have LoadCase as variable

2022-10-03 10:39 UTC, jarabroz commented on includes/Loading/RsectionLoadCombination.js
> +    ASSERT(typeof loadCases != "undefined", "At least one load caes must be defined");
typo

2022-10-03 10:49 UTC, david-liska commented on includes/InternalForces/RsectionInternalForces.js
> +    "U_V" : /*load_cases.E_INTERNAL_FORCES_SYSTEM_PRINCIPAL_AXES_U_V*/"u,v",
There is no value ("u,v", "y,z") - bug?
load_cases.E_INTERNAL_FORCES_SYSTEM_PRINCIPAL_AXES_U_V
load_cases.E_INTERNAL_FORCES_SYSTEM_AXES_X_Y

2022-10-04 08:50 UTC, david-liska commented on includes/InternalForces/RsectionInternalForces.js
> +    "U_V" : /*load_cases.E_INTERNAL_FORCES_SYSTEM_PRINCIPAL_AXES_U_V*/"u,v",
load_cases.E_INTERNAL_FORCES_SYSTEM_PRINCIPAL_AXES_U_V
load_cases.E_INTERNAL_FORCES_SYSTEM_AXES_X_Y
Enums don't return any value,

2022-11-03 10:49 UTC, merged