9512 imperfection
Dlubal-Software/Dlubal_JavaScript_Library pull request #78
Opened 2022-12-05 14:47 UTC by david-liska

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Tests
- [ ] Attached examples
- [ ] Own example attached to Pull Request

**Test Configuration**:
* RFEM / RSTAB / RSECTION version:
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-06 14:01 UTC, jarabroz requested changes

2022-12-06 14:21 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +var memberSet = new MemberSet;
Missing ()

2022-12-06 14:21 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +    var thickness = new Thickness;
Missing ()

2022-12-06 14:21 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +    thickness.Uniform(1, "Thickness", material.GetNo(), 0.250)
Missing semicolon

2022-12-06 14:21 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +    var surfaceSet = new SurfaceSet;
Missing ()

2022-12-06 14:21 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +    var surfaceImperfection = new SurfaceImperfection;
Missing ()

2022-12-06 14:21 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +    var surfaceSetImperfection = new SurfaceSetImperfection;
Missing ()

2022-12-07 07:17 UTC, jarabroz commented on includes/Imperfections/ImperfectionSupport.js
> +        }
Missing semicolon

2022-12-08 15:36 UTC, jarabroz requested changes
Please add imperfection case and local imperfection to steel hall example. There is the old way to create them.

2022-12-08 15:36 UTC, jarabroz commented on includes/BasicObjects/MemberSet.js
> +MemberSet.prototype.MemberSet = function() {
GetMemberSet

2022-12-08 15:36 UTC, jarabroz commented on examples/high_level_functions_demos/imperfections_demo.js
> +member_imperfection.InitialSway(undefined, localIC, [member.GetNo()]);
Make a new variable for this -> it is hard to read. I spent some time to decript it how it works. So I create MemberImperfection object then I use function for selection of type of initial sway.

2022-12-09 09:35 UTC, david-liska commented on includes/Imperfections/ImperfectionCase.js
> +        this.imperfectionCase.level_imperfections.insert_row(row);
There are two way how add and edit rows in table. In this case we get index of new row (row_count()) and then we insert this new row to edit it.

2022-12-09 13:10 UTC, jarabroz approved these changes

2022-12-09 13:10 UTC, merged